// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.mattermost.digitalocean",
  "name": "DigitalOcean Plugin",
  "description": "A DigitalOcean plugin for Mattermost",
  "version": "0.1.0",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "Mattermost plugin for DigitalOcean Teams.",
    "footer": "",
    "settings": [
      {
        "key": "DOTeamID",
        "display_name": "Unique DigitalOcean Team Identifier",
        "type": "text",
        "help_text": "",
        "placeholder": "",
        "default": null
      },
      {
        "key": "DOAdmins",
        "display_name": "DO Admins",
        "type": "text",
        "help_text": "Users that are not system admins on Mattermost but have advanced plugin privileges",
        "placeholder": "",
        "default": null
      },
      {
        "key": "DOAdminToken",
        "display_name": "API token",
        "type": "text",
        "help_text": "Just like a personal token but to be used for general API calls like polling",
        "placeholder": "",
        "default": ""
      },
      {
        "key": "CronConfig",
        "display_name": "Updates schedule",
        "type": "dropdown",
        "help_text": "Define which time zone you'll post bot updates. Default Timezone is US EST.",
        "placeholder": "",
        "default": "CRON_TZ=US/Eastern 30 07 * * *",
        "options": [
          {
            "display_name": "Demo, every minute",
            "value": "*/1 * * * *"
          },
          {
            "display_name": "7:30 am East Africa time",
            "value": "CRON_TZ=Africa/Nairobi 30 07 * * *"
          },
          {
            "display_name": "7:30 am Tokyo time",
            "value": "CRON_TZ=Asia/Tokyo 30 07 * * *"
          },
          {
            "display_name": "7:30 am EST",
            "value": "CRON_TZ=US/Eastern 30 07 * * *"
          },
          {
            "display_name": "7:30 am PST",
            "value": "CRON_TZ=US/Pacific 30 07 * * *"
          }
        ]
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
